apiVersion: v1
kind: ServiceAccount
metadata:
  name: medical-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: medical-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: medical-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: medical-sa
  namespace: default
roleRef:
  kind: Role
  name: medical-role
  apiGroup: rbac.authorization.k8s.io
