apiVersion: v1
kind: Service
metadata:
  name: medical-backend-service
spec:
  selector:
    app: medical-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30081  
